import type { ServiceItem, PortfolioItem, PricingTier } from '@shared/schema';

export const instituteServices: ServiceItem[] = [
  {
    id: 'exam-docs',
    title: 'Exam Documentation',
    description: 'Professional formatting, typing, and confidential handling of examination papers with secure delivery.',
    icon: 'file-text',
    features: [
      'Question paper typing (Hindi/English)',
      'Confidential formatting & page setup',
      'Room-wise seating sheets',
      'Bundle sheets & instruction pages',
      'Digital PDF delivery',
    ],
    category: 'institute',
  },
  {
    id: 'up-scholarship',
    title: 'UP Scholarship Processing',
    description: 'Complete scholarship processing support including forwarding, authentication, and error resolution.',
    icon: 'graduation-cap',
    features: [
      'Technical forwarding',
      'Biometric authentication',
      'DSC locking (in-presence)',
      'Bulk list checking',
      'Error fixing & normalization',
    ],
    category: 'institute',
  },
  {
    id: 'udise-data',
    title: 'UDISE+ Data Management',
    description: 'Comprehensive UDISE+ portal management for student data, promotions, and institutional records.',
    icon: 'database',
    features: [
      'Student promotion & admissions',
      'Teacher profile updates',
      'Aadhaar validation',
      'School report card download',
      'Final certification handover',
    ],
    category: 'institute',
  },
  {
    id: 'govt-projects',
    title: 'Government & Special Projects',
    description: 'Rapid execution of government portal tasks, bulk participation, and deadline-driven projects.',
    icon: 'building-2',
    features: [
      'Student/teacher project uploads',
      'Bulk awareness participation',
      'Exam centre mapping data',
      'Science/exhibition registration',
      'Rapid deadline completion',
    ],
    category: 'institute',
  },
  {
    id: 'daily-support',
    title: 'Daily Digital Support',
    description: 'Remote support for everyday digital tasks including typing, formatting, and instant delivery.',
    icon: 'headphones',
    features: [
      'Notice typing (Hindi/English)',
      'File merge/resize/convert',
      'Certificate name batches',
      'Remote timetable setup',
      'Instant WhatsApp delivery',
    ],
    category: 'institute',
  },
];

export const creativeServices: ServiceItem[] = [
  {
    id: 'video-editing',
    title: 'Video Editing & Post Production',
    description: 'Cinema-grade video editing for YouTube, social media, documentaries, and educational content.',
    icon: 'video',
    features: [
      'YouTube long-form editing',
      'Reels/Shorts retention editing',
      'Documentary storytelling',
      'Sound mastering',
      'Cinematic transitions',
    ],
    category: 'creative',
  },
  {
    id: 'branding',
    title: 'Branding & Graphic Design',
    description: 'Complete visual identity systems from thumbnails to brand guidelines that command attention.',
    icon: 'palette',
    features: [
      'CTR-optimized thumbnails',
      'Event & program posters',
      'Instagram creatives',
      'Business logos & cards',
      'Brand identity systems',
    ],
    category: 'creative',
  },
  {
    id: 'motion-vfx',
    title: 'Motion Graphics & VFX',
    description: 'Dynamic motion design and visual effects that bring your brand and content to life.',
    icon: 'sparkles',
    features: [
      'Logo intro animations',
      'Lower thirds & overlays',
      'Green screen compositing',
      'Visual explainers',
      'Product showcase graphics',
    ],
    category: 'creative',
  },
  {
    id: 'content-strategy',
    title: 'Content Strategy & Growth',
    description: 'Strategic content planning and channel optimization for sustainable audience growth.',
    icon: 'trending-up',
    features: [
      'Scriptwriting (hook-body-close)',
      'SEO keywords & metadata',
      'Publishing optimization',
      'Content calendar setup',
      'Channel growth management',
    ],
    category: 'creative',
  },
];

export const portfolioItems: PortfolioItem[] = [
  {
    id: 'edu-channel',
    title: 'Educational YouTube Channel',
    category: 'Video Editing',
    description: 'Complete channel transformation with consistent branding and retention-focused editing.',
    thumbnail: '',
    tags: ['YouTube', 'Education', 'Long-form'],
  },
  {
    id: 'startup-brand',
    title: 'Tech Startup Branding',
    category: 'Branding',
    description: 'Full brand identity including logo, colors, typography, and marketing collateral.',
    thumbnail: '',
    tags: ['Identity', 'Logo', 'Guidelines'],
  },
  {
    id: 'product-launch',
    title: 'Product Launch Video',
    category: 'Motion Graphics',
    description: 'Cinematic product reveal with 3D-style animations and dynamic transitions.',
    thumbnail: '',
    tags: ['Motion', 'Product', 'Launch'],
  },
  {
    id: 'school-docs',
    title: 'Institution Documentation',
    category: 'Institute Service',
    description: 'Confidential exam paper processing and UDISE+ management for 50+ schools.',
    thumbnail: '',
    tags: ['Documentation', 'Secure', 'Bulk'],
  },
  {
    id: 'social-campaign',
    title: 'Social Media Campaign',
    category: 'Content Strategy',
    description: 'Month-long campaign with 40+ creatives driving 300% engagement increase.',
    thumbnail: '',
    tags: ['Social', 'Strategy', 'Growth'],
  },
  {
    id: 'explainer-series',
    title: 'Explainer Video Series',
    category: 'Motion Graphics',
    description: 'Series of animated explainers simplifying complex technical concepts.',
    thumbnail: '',
    tags: ['Animation', 'Education', 'Series'],
  },
];

export const pricingTiers: PricingTier[] = [
  {
    id: 'per-task',
    name: 'Per-Task Service',
    description: 'Flexible pricing for individual projects and one-time needs.',
    type: 'per-task',
    features: [
      'Pay only for what you need',
      'Quick turnaround times',
      'Direct communication',
      'Quality assurance included',
      'Revision rounds included',
      'Digital delivery',
    ],
    ctaText: 'Get Quote',
  },
  {
    id: 'monthly',
    name: 'Monthly Retainer',
    description: 'Consistent support with priority access and dedicated resources.',
    type: 'monthly',
    features: [
      'Priority queue access',
      'Dedicated support channel',
      'Monthly task allocation',
      'Rollover unused hours',
      'Strategic consultations',
      'Emergency support included',
      'Discounted additional work',
    ],
    highlight: true,
    ctaText: 'Start Partnership',
  },
  {
    id: 'annual',
    name: 'Annual Partnership',
    description: 'Enterprise-grade partnership for institutions and organizations.',
    type: 'annual',
    features: [
      'Comprehensive annual plan',
      'Dedicated account manager',
      'Unlimited revisions',
      'On-site support available',
      'Custom workflow integration',
      'Priority emergency response',
      'Quarterly strategy reviews',
      'Training sessions included',
    ],
    ctaText: 'Contact for Details',
  },
];
